version: 2

jobs:
    build-and-test:
        macos:
            xcode: "9.2.0"
        steps:
            - checkout
            - run:
                name: Run tests
                command: set -o pipefail && xcodebuild clean build test -project Demo.xcodeproj -scheme "Tests" -destination 'platform=iOS Simulator,name=iPhone 7' | xcpretty --color && exit ${PIPESTATUS[0]}
workflows:
  version: 2
  build-and-test:
      jobs:
          - build-and-test
